on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      # with:
      #   fetch-depth: 0
      
    # - name: PHP Version
    #   run: php --version

    # - name: Validate composer.json and composer.lock
    #   run: composer validate

    # - name: Get Composer cache directory
    #   id: composer-cache
    #   #run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    #   run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    # - name: Cache Composer vendor directory
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ steps.composer-cache.outputs.dir }}
    #     key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-composer-
    # - name: Install PHP dependencies
    #   run: composer install --no-progress --no-dev --optimize-autoloader

    - name: Minify css and js
      run: tools/minify.sh

    - name: 📂 Sync files
      # uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: "win.resistenze.org"
        remote-user: "236291@aruba.it"
        remote-password: "!Pisa340.23"
        #ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        remote-path: "/resistenze.org/sito3"
        local-path: "./"



        
